export const FORM_DATA = "FORM_DATA";
export const FORM_DELETE = "FORM_DELETE";

export const ADD_DATA_LOADING = "ADD_DATA_LOADING";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const ADD_DATA_ERROR = "ADD_DATA_ERROR";
export const CLEAR_ADD_DATA_ERROR = "CLEAR_ADD_DATA_ERROR";

export const FETCH_DATA_LOADING = "FETCH_DATA_LOADING";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";

export const FETCH_DATA_SUCCESS_NEWS = "FETCH_DATA_SUCCESS_NEWS";
export const FETCH_DATA_NEWS_DETAIL = "FETCH_DATA_NEWS_DETAIL";

export const FETCH_DATA_SETTING = "FETCH_DATA_SETTING";
export const CHG_PROPS = "CHG_PROPS";

export const FETCH_DATA_PRICELIST = "FETCH_DATA_PRICELIST";
export const FETCH_DATA_LEVEL = "FETCH_DATA_LEVEL";

export const FETCH_DATA_VOUCHERS = "FETCH_DATA_VOUCHERS";
export const CONFIRM_PUBLISH_VOUCHER = "CONFIRM_PUBLISH_VOUCHER";

export const FETCH_DATA_BLAST = "FETCH_DATA_BLAST";
